import "maplibre-gl/dist/maplibre-gl.css";
import "./style.css";
import type { Candidate, HistoricalMapLayer, InvestigationResult } from "./types";
import type { Map as MapLibreMap } from "maplibre-gl";

type Lang = "zh" | "en";
type RelatedStreet = {street_id:string;score:number;reason_zh:string;reason_en:string};
type CatalogStreet = { id:string; address:string; name_zh:string; name_en:string; district_zh:string; district_en:string; period_zh:string; period_en:string; intro_zh:string; intro_en:string; themes_zh:string[]; themes_en:string[]; cover:string; center:[number,number]; related?:RelatedStreet[] };

const app = document.querySelector<HTMLDivElement>("#app")!;
const state:{lang:Lang;catalog:CatalogStreet[];active:CatalogStreet|null;result:InvestigationResult|null;map:MapLibreMap|null}={lang:"zh",catalog:[],active:null,result:null,map:null};
const esc=(v:unknown)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]!);
const api=async(path:string,options?:RequestInit)=>{const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");return data};
const tr=<T,>(zh:T,en:T)=>state.lang==="zh"?zh:en;

const featureEnglish:Record<string,string>={"刘海粟近作展览会":"Exhibition of Liu Haisu’s Recent Works","康健书局创办":"Kangjian Bookstore founded","国泰电影院":"Cathay Theatre","新式里弄":"New-style lane housing","国际礼拜堂":"Shanghai Community Church","西湖公寓":"West Lake Apartments","衡山宾馆":"Hengshan Hotel","集雅公寓":"Georgia Apartments","万宜坊":"Wanyi Lane","重庆公寓":"Chongqing Apartments","原卢湾区政府2号楼":"Former Luwan District Government Building No. 2","亚尔培坊":"King Albert Lane","凡尔登花园":"Verdun Garden","静安别墅":"Jing’an Villas","上海美术馆":"Shanghai Art Museum","国际饭店":"Park Hotel","泰兴大楼":"Taixing Building","南京西路931号公寓":"Apartment at 931 West Nanjing Road","多伦路始建":"Duolun Road established","鸿德堂":"Hongde Church","永安里前期住宅竣工":"First phase of Yong’an Lane completed","大桥大楼":"Bridge House","华德路监狱启用":"Ward Road Gaol opened","摩西会堂":"Ohel Moishe Synagogue","外滩信号台建成":"Bund Signal Tower completed","和平饭店北楼":"Peace Hotel North Building"};
const descriptionEnglish:Record<string,string>={
  "刘海粟近作展览会":"In 1927, Liu Haisu presented an exhibition of recent work at the Shangxian Hall on Avenue Joffre; contemporary notices appeared in Shibao and Shanghai Pictorial.",
  "康健书局创办":"Kangjian Bookstore was founded in 1934 at 436 Avenue Joffre (today’s Huaihai Middle Road) and remained active until 1950.",
  "新式里弄":"This new-style lane compound at 300 Hengshan Road records the emergence of denser residential forms along the street in 1920.",
  "国际礼拜堂":"The Shanghai Community Church, completed in 1925, became a major public institution on the former Avenue Pétain.",
  "西湖公寓":"West Lake Apartments, dated to 1928 in the building record, illustrates the street’s expanding apartment landscape.",
  "万宜坊":"Wanyi Lane was developed from 1923 and records the long presence of lane housing along South Chongqing Road.",
  "重庆公寓":"Chongqing Apartments, dated to 1931, represents the growth of multi-unit urban housing on the road.",
  "亚尔培坊":"King Albert Lane, recorded from 1920, connects the street’s former French name with its residential compounds.",
  "凡尔登花园":"Verdun Garden was developed between 1925 and 1929, adding garden residences to the street’s varied housing fabric.",
  "静安别墅":"Jing’an Villas, completed in 1932, form one of the best-known lane compounds on West Nanjing Road.",
  "上海美术馆":"The building record links the former Shanghai Art Museum to 325 West Nanjing Road, marking the commercial axis’s civic-cultural role in 2012."
  ,"多伦路始建":"Hongkou District records that the road was established in 1911 under the name Darroch Road, providing the starting point for this dossier.",
  "鸿德堂":"Shanghai Library’s historic-building record dates the construction of Hongde Church from 1925 to its completion in 1928.",
  "永安里前期住宅竣工":"Hongkou District records that the first phase of Yong’an Lane, facing North Sichuan Road, was completed in 1925.",
  "大桥大楼":"Shanghai Library’s historic-building record dates the former Bridge Apartments to 1935.",
  "华德路监狱启用":"The Shanghai Gazetteer records that Ward Road Gaol, later Tilanqiao Prison, opened in 1903.",
  "摩西会堂":"The building began in 1907 and was converted into the Ohel Moishe Synagogue in 1927 at 62 Ward Road, today’s Changyang Road.",
  "外滩信号台建成":"Shanghai’s protected-heritage register dates the Bund Signal Tower at 1A East Zhongshan No. 2 Road to 1907.",
  "和平饭店北楼":"The north building was completed in 1929 as the Cathay Hotel at 20 East Zhongshan No. 1 Road."
};
const datasetEnglish:Record<string,string>={"上海市历史文化事件知识库":"Shanghai Historical and Cultural Events Knowledge Base","上海优秀历史建筑":"Shanghai Historic Buildings","上海地名志·道路实体":"Shanghai Gazetteer of Place Names — Roads"};
const editorialEssays:Record<string,{zh:string[];en:string[]}>={
  xiafei:{zh:["这条道路的历史并非一次简单更名。1901年至1950年间的六个名称阶段，映照了法租界市政扩展、战时改名与新中国成立后的城市命名调整。","现有事件记录把1927年的刘海粟展览和1934年的康健书局定位在霞飞路上，使商业街景之外的出版、美术与文化交往变得可见。"],en:["The road’s history is more than a single renaming. Six name periods between 1901 and 1950 reflect concession expansion, wartime changes and the remaking of Shanghai’s civic geography after 1949.","Records of Liu Haisu’s 1927 exhibition and the 1934 founding of Kangjian Bookstore reveal publishing, art and cultural exchange behind the familiar commercial streetscape."]},
  hengshan:{zh:["贝当路时期形成的住宅与公共建筑，使衡山路成为观察近代上海居住方式变化的一条剖面。里弄、独立公寓和宗教建筑在同一道路上并存。","1920年代的新式里弄、国际礼拜堂与西湖公寓分别呈现人口密度、公共交往和公寓生活的发展，也解释了道路风貌为何具有连续而多样的层次。"],en:["Housing and public buildings from the Avenue Pétain period make Hengshan Road a cross-section of changing urban life. Lane compounds, apartments and a church coexist along one route.","The 1920 lane housing, Community Church and West Lake Apartments show changing density, public association and apartment living, explaining the street’s layered character."]},
  chongqing:{zh:["重庆南路的档案重点不是单座名建筑，而是里弄与公寓如何共同构成近代城市住宅。万宜坊和重庆公寓记录了从低层弄堂到集合住宅的并置。","道路在1943年至1946年间曾使用灵宝路之名。名称变化与住宅形态的连续存在形成对照：行政命名可以迅速改变，街区生活则往往延续更久。"],en:["The dossier focuses less on a single monument than on how lane housing and apartments formed the modern residential city. Wanyi Lane and Chongqing Apartments record two forms side by side.","The name Lingbao Road was used between 1943 and 1946. Rapid administrative renaming contrasts with the longer continuity of neighbourhood life."]},
  shaanxi:{zh:["陕西南路穿过不同街区，花园住宅、新式里弄与沿街商业共同存在。亚尔培坊和凡尔登花园提供了两种住宅组织方式的具体坐标。","1946年的定名把此前短暂使用的咸阳路纳入新的城市路名体系。今天的街景仍可帮助观察历史住宅与当代交通、商业之间的关系。"],en:["South Shaanxi Road crosses several neighbourhoods where garden residences, lane housing and commerce coexist. King Albert Lane and Verdun Garden locate two distinct residential forms.","The 1946 name replaced the short-lived Xianyang Road. Today’s streetscape still reveals how historic housing meets contemporary transport and commerce."]},
  nanjingwest:{zh:["从静安寺路到南京西路，这条道路逐渐成为连接商业、旅馆、公寓与公共文化设施的城市轴线。静安别墅展示了商业大道背后的日常居住空间。","1932年的静安别墅与2012年的公共文化建筑记录相隔八十年，说明道路并非停留在单一的黄金年代，而是在持续转换功能。"],en:["From Bubbling Well Road to West Nanjing Road, the route became an axis of commerce, hotels, apartments and civic culture. Jing’an Villas reveal everyday housing behind the avenue.","The gap between the 1932 villas and a 2012 civic-cultural record shows a street that kept changing function rather than remaining fixed in one golden age."]},
  duolun:{zh:["多伦路始建于1911年，早期名为窦乐安路。道路尺度不大，却汇集宗教建筑、里弄住宅、文学活动与革命遗址，形成高度集中的文化地景。","鸿德堂的建设年代和永安里分期形成的街区，共同说明文化名人活动并非发生在抽象地名中，而是嵌入具体住宅、会堂和街巷。"],en:["Established in 1911 as Darroch Road, this short street concentrates churches, lane housing, literary activity and revolutionary sites into a dense cultural landscape.","The construction of Hongde Church and the phased development of Yong’an Lane show that cultural history unfolded within specific homes, halls and lanes."]},
  sichuan:{zh:["四川北路既是商业道路，也是虹口居住和文化活动的重要轴线。大桥大楼与永安里分别呈现公寓和大规模里弄住宅两类城市生活。","永安里1925年竣工的前期住宅后来成为革命活动地点。建筑用途与居住者变化，使同一处空间连接商业企业、职员生活和政治历史。"],en:["North Sichuan Road is both a commercial route and an axis of residential and cultural life in Hongkou. Bridge House and Yong’an Lane represent apartments and large lane compounds.","The first phase of Yong’an Lane, completed in 1925, later became associated with revolutionary activity, linking corporate housing, everyday life and political history."]},
  changyang:{zh:["华德路时期形成的监狱与会堂，使今天的长阳路保存了制度管理和移民社群两种截然不同的历史空间。","1903年启用的监狱与1927年改作会堂的摩西会堂，后来都成为提篮桥历史文化街区的重要组成。二战期间犹太难民的到来又赋予该地区新的世界性联系。"],en:["The former Ward Road preserves two contrasting institutional landscapes: a prison associated with civic control and a synagogue associated with migrant community life.","The prison opened in 1903 and Ohel Moishe took its synagogue form in 1927. Both later became anchors of the Tilanqiao historic district, reshaped again by Jewish refuge during the Second World War."]},
  bund:{zh:["外滩的历史价值来自建筑群、江岸交通与城市天际线的共同形成，而非任何一栋建筑。十九世纪照片仍能显示连续街墙形成之前的滨江尺度。","1907年的信号台服务于黄浦江航运，1929年的华懋饭店则代表金融和旅馆建筑的成熟。两者把基础设施、公共服务与城市形象连接在同一段江岸。"],en:["The Bund’s significance lies in the combined formation of its building ensemble, river traffic and skyline rather than in any single landmark. Nineteenth-century photographs show the waterfront before its continuous street wall matured.","The 1907 Signal Tower served Huangpu River navigation, while the 1929 Cathay Hotel represented mature financial and hotel architecture—linking infrastructure, public service and city image."]}
};
const ui={
  zh:{archive:"上海街道历史档案",tagline:"沿着一条上海街道，阅读它的名称、人物、建筑与时代变迁。",choose:"选择一条街道",filter:"在已完成的街道档案中筛选",all:"全部",enter:"进入街道档案",back:"返回街道目录",export:"导出阅读版",loading:"正在打开街道档案",loadingNote:"整理道路名称、历史节点、影像与资料来源。",overview:"街道概览",names:"名称沿革",chronicle:"街道纪事",images:"街道影像",place:"街道与城市",sources:"资料来源",related:"继续阅读",relatedMethod:"经 GPU 双语语义比较生成，并限定在已审核档案内",source:"查看资料依据",visual:"查看图像信息",mapReason:"这幅1943年上海地图用于观察道路在近代城市路网中的位置；标记点表示本档案涉及的建筑或事件。",research:"编者注",researchText:"仅保留有明确年代的历史节点。个别地点精度止于道路或门牌范围，具体说明附在相应资料中。",noMatch:"目录中没有符合当前筛选的街道。",sourceHelp:"以下资料共同支撑本页的名称、建筑与事件叙述。打开条目可查看记录内容与馆藏入口。"},
  en:{archive:"Shanghai Street History Archive",tagline:"Follow one Shanghai street through its names, people, buildings and transformations.",choose:"Choose a street",filter:"Filter the completed street dossiers",all:"All",enter:"Open street dossier",back:"Back to catalogue",export:"Export reader edition",loading:"Opening the street dossier",loadingNote:"Assembling names, dated moments, images and sources.",overview:"Overview",names:"Names through time",chronicle:"Street chronicle",images:"Visual archive",place:"Street in the city",sources:"Sources",related:"Continue exploring",relatedMethod:"Generated through GPU-assisted bilingual comparison and limited to reviewed dossiers",source:"View supporting source",visual:"View image record",mapReason:"This 1943 map locates the road within Shanghai’s modern street network; markers identify buildings or events discussed in this dossier.",research:"Editorial note",researchText:"Only dated historical moments appear in the chronology. Some locations are known only to street or address level; details appear with their sources.",noMatch:"No published street matches these filters.",sourceHelp:"Together, these records support the names, buildings and events presented above. Open an entry for its record details and collection link."}
};
const t=()=>ui[state.lang];

function shell(){
  app.innerHTML=`<div class="shell"><header class="topbar"><button class="brand" id="brandBtn"><span class="brand-mark">文</span><span><b>文脉镜 ContextLens</b><small>${esc(t().archive)}</small></span></button><div class="top-actions"><button class="lang-switch" id="langBtn">${state.lang==="zh"?"EN":"中文"}</button></div></header><main id="view"></main><div class="progress" id="progress"><div><span class="spinner"></span><h2>${esc(t().loading)}</h2><p>${esc(t().loadingNote)}</p></div></div><div class="modal-backdrop" id="backdrop"></div><aside class="source-drawer" id="drawer" aria-hidden="true"><button class="drawer-close" id="drawerClose">×</button><div id="drawerBody"></div></aside><div class="toast" id="toast"></div></div>`;
  document.getElementById("brandBtn")!.addEventListener("click",renderHome);
  document.getElementById("langBtn")!.addEventListener("click",()=>{state.lang=state.lang==="zh"?"en":"zh";shell();state.result&&state.active?renderDossier():renderHome()});
  document.getElementById("drawerClose")!.addEventListener("click",closeDrawer);document.getElementById("backdrop")!.addEventListener("click",closeDrawer);
}

function renderHome(){
  state.result=null;state.active=null;if(state.map){state.map.remove();state.map=null}closeDrawer();
  const districts=[...new Set(state.catalog.map(x=>state.lang==="zh"?x.district_zh:x.district_en))];
  document.getElementById("view")!.innerHTML=`<section class="catalog-hero"><div class="map-paper" aria-hidden="true"></div><div class="hero-intro"><p class="kicker">CONTEXTLENS · SHANGHAI</p><h1>文脉镜 <span>ContextLens</span></h1><h2>${esc(t().archive)}</h2><p>${esc(t().tagline)}</p></div><div class="catalog-panel"><div class="catalog-heading"><div><span>${esc(t().choose)}</span><b>${String(state.catalog.length).padStart(2,"0")}</b></div><label><span class="sr-only">${esc(t().filter)}</span><input id="filterInput" placeholder="${esc(t().filter)}"><i>⌕</i></label></div><div class="filters" id="filters"><button class="active" data-filter="">${esc(t().all)}</button>${districts.map(d=>`<button data-filter="${esc(d)}">${esc(d)}</button>`).join("")}</div><div class="catalog-grid" id="catalogGrid"></div></div></section><footer class="site-foot"><span>文脉镜 ContextLens</span><span>${state.lang==="zh"?"数据基础：上海图书馆开放数据及注明来源的公共馆藏":"Data foundation: Shanghai Library open data and credited public collections"}</span></footer>`;
  let district="";const input=document.getElementById("filterInput") as HTMLInputElement;
  const draw=()=>{const q=input.value.trim().toLowerCase();const rows=state.catalog.filter(x=>{const hay=[x.name_zh,x.name_en,x.district_zh,x.district_en,...x.themes_zh,...x.themes_en].join(" ").toLowerCase();const d=state.lang==="zh"?x.district_zh:x.district_en;return(!q||hay.includes(q))&&(!district||d===district)});document.getElementById("catalogGrid")!.innerHTML=rows.length?rows.map(catalogCard).join(""):`<p class="catalog-empty">${esc(t().noMatch)}</p>`;document.querySelectorAll<HTMLButtonElement>("[data-street]").forEach(b=>b.onclick=()=>openStreet(b.dataset.street||""));wireImageFallbacks()};
  input.oninput=draw;document.querySelectorAll<HTMLButtonElement>("[data-filter]").forEach(b=>b.onclick=()=>{district=b.dataset.filter||"";document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));draw()});draw();
}

function catalogCard(item:CatalogStreet){const themes=state.lang==="zh"?item.themes_zh:item.themes_en;return `<article class="catalog-card"><button data-street="${esc(item.id)}"><div class="card-image"><img src="${esc(item.cover)}" alt="" loading="lazy"><span>${esc(state.lang==="zh"?item.period_zh:item.period_en)}</span></div><div class="card-copy"><small>${esc(state.lang==="zh"?item.district_zh:item.district_en)}</small><h3>${esc(state.lang==="zh"?item.name_zh:item.name_en)}</h3><p>${esc(state.lang==="zh"?item.intro_zh:item.intro_en)}</p><div>${themes.map(x=>`<i>${esc(x)}</i>`).join("")}</div><b>${esc(t().enter)} →</b></div></button></article>`}

async function openStreet(id:string){const item=state.catalog.find(x=>x.id===id);if(!item)return;state.active=item;document.getElementById("progress")!.classList.add("open");try{const resolved=await api("/api/place/resolve",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address:item.address,allow_live:false})});if(!resolved.candidates?.length)throw new Error("Catalogue record unavailable");const candidate:Candidate=resolved.candidates[0];const job=await api("/api/investigations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({address:item.address,candidate,allow_live:false})});for(let n=0;n<100;n++){const current=await api(`/api/investigations/${job.id}`);if(current.status==="complete"){state.result=current.result;document.getElementById("progress")!.classList.remove("open");renderDossier();return}if(current.status==="failed")throw new Error(current.error);await new Promise(r=>setTimeout(r,100))}throw new Error("Timeout")}catch(e){document.getElementById("progress")!.classList.remove("open");toast(state.lang==="zh"?"街道档案暂时无法打开":"The street dossier could not be opened")}}

function renderDossier(){if(!state.result||!state.active)return;if(state.map){state.map.remove();state.map=null}const r=state.result,c=state.active;const timeline=(r.timeline||[]).filter((x:any)=>x.start_year||x.date);const periods=(r.candidate.name_periods||[]).filter((x:any)=>x.from_year||x.to_year);const media=r.media||[];const maps=r.experience?.historical_maps||[];const map=maps.find((x:HistoricalMapLayer)=>x.map_id==="princeton-1943")||maps[0];const lead=media[0];const relationRows=(c.related||[]).map(relation=>({relation,street:state.catalog.find(item=>item.id===relation.street_id)})).filter(item=>item.street).slice(0,3);
  document.getElementById("view")!.innerHTML=`<nav class="dossier-bar"><button id="backBtn">← ${esc(t().back)}</button><div><a href="#chronicle">${esc(t().chronicle)}</a>${media.length?`<a href="#visuals">${esc(t().images)}</a>`:""}<a href="#sources">${esc(t().sources)}</a></div><button id="printBtn">${esc(t().export)}</button></nav><article class="dossier">
  <header class="dossier-cover" style="--cover:url('${esc(lead?.image_url||c.cover)}')"><div class="cover-shade"></div><div class="cover-copy"><p>${esc(state.lang==="zh"?c.district_zh:c.district_en)} · ${esc(state.lang==="zh"?c.period_zh:c.period_en)}</p><h1>${esc(state.lang==="zh"?c.name_zh:c.name_en)}</h1><p>${esc(state.lang==="zh"?c.intro_zh:c.intro_en)}</p><div>${(state.lang==="zh"?c.themes_zh:c.themes_en).map(x=>`<span>${esc(x)}</span>`).join("")}</div></div></header>
  <section class="editorial-overview"><header><small>01</small><h2>${state.lang==="zh"?"读懂这条街":"Reading the street"}</h2></header><div>${(editorialEssays[c.id]?.[state.lang]||[]).map(p=>`<p>${esc(p)}</p>`).join("")}</div></section>
  ${periods.length>1?`<section class="name-story"><header><small>02</small><h2>${esc(t().names)}</h2></header><div class="name-track">${periods.map((p:any,i:number)=>`<article><time>${p.from_year?`${p.from_year}`:state.lang==="zh"?`${p.to_year}年前`:`Before ${p.to_year}`}${p.to_year?`—${p.to_year}`:state.lang==="zh"?"—至今":"—present"}</time><h3>${esc(p.name)}</h3><p>${esc(nameContext(p.name,i,periods.length))}</p></article>`).join("")}</div></section>`:""}
  <section class="chronicle" id="chronicle"><header><small>${periods.length>1?"03":"02"}</small><h2>${esc(t().chronicle)}</h2></header><div class="chronicle-list">${timeline.map((x:any,i:number)=>moment(x,i,r.evidence||[])).join("")}</div></section>
  ${media.length?`<section class="visuals" id="visuals"><header><small>03</small><h2>${esc(t().images)}</h2></header><div class="visual-grid">${media.map((x:any)=>{const title=state.lang==="en"?(x.title_en||x.title):x.title;const desc=state.lang==="en"?(x.description_en||x.description):x.description;return `<figure><button data-media="${esc(x.asset_id)}"><img src="${esc(x.image_url)}" alt="${esc(title)}" loading="lazy"><span>${esc(t().visual)} ↗</span></button><figcaption><time>${esc(x.year)}</time><h3>${esc(title)}</h3><p>${esc(desc)}</p><small>${esc(x.provider)} · ${esc(x.creator)}</small></figcaption></figure>`}).join("")}</div></section>`:""}
  ${map?`<section class="place-chapter"><div class="place-copy"><small>04</small><h2>${esc(t().place)}</h2><p>${esc(t().mapReason)}</p><dl><dt>${state.lang==="zh"?"地图":"Map"}</dt><dd>${esc(map.title)}</dd><dt>${state.lang==="zh"?"年代":"Year"}</dt><dd>${esc(map.year)}</dd><dt>${state.lang==="zh"?"馆藏":"Collection"}</dt><dd>${esc(map.provider)}</dd></dl><a href="${esc(map.source_url)}" target="_blank" rel="noopener noreferrer">${state.lang==="zh"?"查看地图馆藏记录":"Open map collection record"} ↗</a></div><div class="place-map"><div id="modernMap"></div></div></section>`:""}
  <aside class="research-note"><b>${esc(t().research)}</b><p>${esc(t().researchText)}</p></aside>
  <section class="sources" id="sources"><header><small>05</small><h2>${esc(t().sources)}</h2><p>${esc(t().sourceHelp)}</p></header><div class="source-list">${(r.evidence||[]).map((x:any)=>sourceRow(x)).join("")}</div></section>
  <section class="related"><small>${esc(t().related)}</small><p>${esc(t().relatedMethod)}</p><div>${relationRows.map(({relation,street})=>`<button data-related="${esc(street!.id)}"><span>${esc(state.lang==="zh"?street!.district_zh:street!.district_en)}</span><b>${esc(state.lang==="zh"?street!.name_zh:street!.name_en)}</b><em>${esc(state.lang==="zh"?relation.reason_zh:relation.reason_en)}</em><i>→</i></button>`).join("")}</div></section></article>`;
  document.getElementById("backBtn")!.onclick=renderHome;document.getElementById("printBtn")!.onclick=()=>window.print();document.querySelectorAll<HTMLButtonElement>("[data-source]").forEach(b=>b.onclick=()=>openSource(b.dataset.source||""));document.querySelectorAll<HTMLButtonElement>("[data-media]").forEach(b=>b.onclick=()=>openMedia(b.dataset.media||""));document.querySelectorAll<HTMLButtonElement>("[data-related]").forEach(b=>b.onclick=()=>openStreet(b.dataset.related||""));wireImageFallbacks();void initMap();window.scrollTo({top:0});
}

function wireImageFallbacks(){const fallback="https://commons.wikimedia.org/wiki/Special:Redirect/file/Shanghai%20Map%201954.jpg?width=1400";document.querySelectorAll<HTMLImageElement>("img").forEach(img=>img.onerror=()=>{img.onerror=null;img.src=fallback;img.classList.add("image-fallback")})}

function nameContext(name:string,index:number,total:number){if(state.lang==="zh")return index===total-1?"沿用至今的道路名称。":"这一名称阶段由道路实体记录确认；相关年代与后续名称共同构成更名序列。";return index===total-1?"The street’s present-day name.":"Road authority records establish this period within the documented sequence of names."}
function moment(x:any,index:number,evidence:any[]){const source=evidence.find((e:any)=>e.evidence_id===x.feature_id);const title=state.lang==="zh"?x.title:(featureEnglish[x.title]||x.title);const raw=source?.description||source?.snippet||x.address||"";const desc=state.lang==="en"?(descriptionEnglish[x.title]||raw):raw;return `<article class="moment"><div><time>${esc(x.time_label||x.start_year)}</time><span>${String(index+1).padStart(2,"0")}</span></div><div><h3>${esc(title)}</h3><p>${esc(desc)}</p>${x.address?`<address>${esc(x.address)}</address>`:""}<button data-source="${esc(x.feature_id)}">${esc(t().source)} →</button></div></article>`}
function sourceRow(x:any){const id=x.evidence_id||x.record_id;const provider=x.lineage?.provider||x.provider||"上海图书馆";const title=state.lang==="en"?(datasetEnglish[x.source_title]||featureEnglish[x.title]||x.source_title||x.title):(x.source_title||x.title);const raw=x.description||x.snippet||"";const desc=state.lang==="en"?(descriptionEnglish[x.title]||raw):raw;return `<button data-source="${esc(id)}"><span><small>${esc(provider)}</small><b>${esc(title)}</b><p>${esc(desc.slice(0,160))}</p></span><i>↗</i></button>`}

function openSource(id:string){const r=state.result;if(!r)return;const x=(r.evidence||[]).find((e:any)=>e.evidence_id===id||e.record_id===id);if(!x)return;const uri=x.source_uri||x.lineage?.official_uri||"";const title=state.lang==="en"?(datasetEnglish[x.source_title]||featureEnglish[x.title]||x.source_title||x.title):(x.source_title||x.title);const raw=x.description||x.snippet||"";const desc=state.lang==="en"?(descriptionEnglish[x.title]||raw):raw;openDrawer(`<p class="drawer-kicker">${esc(t().sources)}</p><h2>${esc(title)}</h2><blockquote>${esc(desc)}</blockquote><dl><dt>${state.lang==="zh"?"提供机构":"Provider"}</dt><dd>${esc(x.lineage?.provider||x.provider||"上海图书馆")}</dd><dt>${state.lang==="zh"?"资料集":"Collection"}</dt><dd>${esc(x.dataset_label||x.dataset||"")}</dd><dt>${state.lang==="zh"?"与本页关系":"Contribution"}</dt><dd>${state.lang==="zh"?"支持本页对应的道路、建筑或事件叙述。":"Supports the corresponding road, building or event account on this page."}</dd></dl>${uri?`<a class="drawer-link" href="${esc(uri)}" target="_blank" rel="noopener noreferrer">${state.lang==="zh"?"打开馆藏原始记录":"Open original collection record"} ↗</a>`:""}`)}
function openMedia(id:string){const x=state.result?.media?.find((e:any)=>e.asset_id===id);if(!x)return;const title=state.lang==="en"?(x.title_en||x.title):x.title;const desc=state.lang==="en"?(x.description_en||x.description):x.description;openDrawer(`<p class="drawer-kicker">${esc(t().images)}</p><h2>${esc(title)}</h2><img class="drawer-image" src="${esc(x.image_url)}" alt=""><p>${esc(desc)}</p><dl><dt>${state.lang==="zh"?"作者":"Creator"}</dt><dd>${esc(x.creator)}</dd><dt>${state.lang==="zh"?"收藏":"Collection"}</dt><dd>${esc(x.provider)}</dd><dt>${state.lang==="zh"?"许可":"Licence"}</dt><dd>${esc(x.license)}</dd><dt>${state.lang==="zh"?"采用理由":"Why included"}</dt><dd>${state.lang==="zh"?"用于观察该道路在相应年代的街景、尺度与沿街环境。":"Included to examine the street’s appearance, scale and surroundings in the stated period."}</dd></dl><a class="drawer-link" href="${esc(x.source_url)}" target="_blank" rel="noopener noreferrer">${state.lang==="zh"?"打开图像原始记录":"Open original image record"} ↗</a>`)}
function openDrawer(html:string){document.getElementById("drawerBody")!.innerHTML=html;document.getElementById("drawer")!.classList.add("open");document.getElementById("backdrop")!.classList.add("open")}
function closeDrawer(){document.getElementById("drawer")?.classList.remove("open");document.getElementById("backdrop")?.classList.remove("open")}
function toast(s:string){const el=document.getElementById("toast")!;el.textContent=s;el.classList.add("open");setTimeout(()=>el.classList.remove("open"),2400)}
async function initMap(){const el=document.getElementById("modernMap");if(!el||!state.result||!state.active)return;try{const ml=await import("maplibre-gl");state.map=new ml.Map({container:el,style:"https://tiles.openfreemap.org/styles/positron",center:state.active.center,zoom:14,attributionControl:{compact:true}});state.map.on("load",()=>{state.map!.addSource("evidence",{type:"geojson",data:state.result!.feature_collection});state.map!.addLayer({id:"points",type:"circle",source:"evidence",paint:{"circle-radius":7,"circle-color":"#e85d3f","circle-stroke-width":3,"circle-stroke-color":"#f3e9d4"}})})}catch{el.innerHTML=`<p>${state.lang==="zh"?"地图暂不可用，街道档案内容不受影响。":"Map temporarily unavailable; the dossier remains available."}</p>`}}

async function boot(){shell();try{const data=await api("/api/catalog");state.catalog=data.streets||[];renderHome()}catch{toast("Catalogue unavailable")}}
void boot();
